name: StreamManager
options:
  minimumXcodeGenVersion: 2.35.0
  deploymentTarget:
    iOS: "13.0"
packages: {}   # 以后需要 SPM 再加
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: "13.0"
    SWIFT_VERSION: "5.0"

targets:
  StreamManager:
    type: application
    platform: iOS
    sources:
      - path: StreamManager
    info:
      path: StreamManager/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourname.StreamManager
        CODE_SIGN_STYLE: Automatic
    scheme:
      testTargets: []
